---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stage-data 
data:
  stage-data.sh: |
    azcopy cp --recursive "<Blob_URI>" /hpccache
---
apiVersion: v1
kind: Pod
metadata:
  name: attach-pvc
spec:
  volumes:
    - name:  nfs
      persistentVolumeClaim:
        claimName: k8s-hpccache
    - name: config
      configMap:
        defaultMode: 420
        items:
        - key: stage-data.sh
          mode: 365
          path: stage-data.sh
        name: stage-data
  containers:
  - name: attach-pvc
    image: amrragab8080/azcopy:latest
    command:
    - sh
    - /etc/config/stage-data.sh
    volumeMounts:
    - name: config
      mountPath: /etc/config
    - name:  nfs 
      mountPath: /hpccache
