apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: tensorflow-benchmarks
spec:
  slotsPerWorker: 4
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
          volumes:
          - name:  nfs
            persistentVolumeClaim:
              claimName: k8-hpccache
          containers:
          - image: mpioperator/tensorflow-benchmarks:latest
            name: tensorflow-benchmarks
            command:
            - mpirun
            - --allow-run-as-root
            - --report-bindings
            - -np
            - "16"
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - NCCL_NSOCKS_PERTHREAD=4
            - -x
            - NCCL_SOCKET_NTHREADS=4
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - python
            - scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py
            - --data_format=NCHW
            - --batch_size=256
            - --model=resnet50
            - --optimizer=momentum
            - --variable_update=horovod
            - --nodistortions
            - --gradient_repacking=8
            - --num_epochs=90
            - --weight_decay=1e-4
            - --data_dir=/hpccache/imagenet/train
            - --use_fp16
            - --train_dir=/hpccache/models/resnet50
            volumeMounts:
            - name:  nfs
              mountPath: /hpccache

    Worker:
      replicas: 4
      template:
        spec:
          volumes:
          - name:  nfs
            persistentVolumeClaim:
              claimName: k8-hpccache
          containers:
          - image: mpioperator/tensorflow-benchmarks:latest
            name: tensorflow-benchmarks
            resources:
              limits:
                nvidia.com/gpu: 4
            volumeMounts:
            - name:  nfs
              mountPath: /hpccache
